### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by qnkhuat** [qnkhuat/gochess#1]
Hey!

I created this issue to receive comments on my code!
Any comments will be much appreciated!

Thank you 🌝

**Comment by quackduck** [comment]
Hey, I'm building something similar. How does this work?

**Comment by quackduck** [comment]
I'm trying to understand the code but it's hard to see where it starts and how it works.

**Comment by qnkhuat** [comment]
I suggest you start with the `/cmd` folder.

The general idea here is:
1. whenever there is an ssh request to gochess, this request will first arrive at my `server` cmd. 
2. The server then [create](https://github.com/qnkhuat/gochess/blob/6877302b31b28c50a1e4b75370336fd3ff397afc/pkg/server.go#L67) a Pseudoterminal and start the `gochess` cmd.
3. If you check the [gochess](https://github.com/qnkhuat/gochess/blob/6877302b31b28c50a1e4b75370336fd3ff397afc/cmd/chessterm/main.go#L16) cmd you will find a `ServerPort` parameter which is the port that `gochess` and `server` use to exchange game requests

I haven't refactored the code so it's a big mess but if you tell me about what you're going to build then I might help you better.

Or you can check out this repo for a better code structure: https://gitlab.com/tslocum/netris
